#!/usr/bin/env python3
"""Generate offline Unicode 16.0 lowercase tables and shared mapping fixtures.

Fetches only versioned public Unicode data; never imports host-runtime casing.
Cached inputs live in .tmp/unicode. --check verifies generated files without edits.
"""
from pathlib import Path
import argparse, hashlib, json, urllib.request
ROOT = Path(__file__).resolve().parents[1]
VERSION = '16.0.0'
HASHES = {
    'UnicodeData.txt': 'ff58e5823bd095166564a006e47d111130813dcf8bf234ef79fa51a870edb48f',
    'SpecialCasing.txt': '8d5de354eef79f2395a54c9c7dcebbaf3d30fc962d0f85611ea97aa973a0c451',
    'DerivedCoreProperties.txt': '39d35161f2954497f69e08bdb9e701493f476a3d30222de20028feda36c1dabd',
}

def source(name):
    path = ROOT/'.tmp/unicode'/name
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(urllib.request.urlopen(f'https://www.unicode.org/Public/{VERSION}/ucd/{name}', timeout=30).read())
    data = path.read_bytes()
    if hashlib.sha256(data).hexdigest() != HASHES[name]: raise SystemExit('Unicode source checksum mismatch: '+name)
    return data.decode('utf8')

def generate():
    mapping = {}
    for line in source('UnicodeData.txt').splitlines():
        fields = line.split(';')
        if fields[13]: mapping[int(fields[0], 16)] = [int(fields[13], 16)]
    for line in source('SpecialCasing.txt').splitlines():
        line = line.split('#')[0].strip()
        if not line: continue
        fields = [s.strip() for s in line.split(';')]
        if not fields[4]: mapping[int(fields[0], 16)] = [int(n, 16) for n in fields[1].split()]
        elif fields[4] == 'Final_Sigma': assert fields[0] == '03A3' and fields[1] == '03C2'
        else: assert fields[4].split()[0] in {'tr','az','lt'}, fields[4]
    mapping = {k:v for k,v in sorted(mapping.items()) if v != [k]}
    properties = {'Cased': [], 'Case_Ignorable': []}
    for line in source('DerivedCoreProperties.txt').splitlines():
        line = line.split('#')[0].strip()
        if not line: continue
        fields = [s.strip() for s in line.split(';')]
        if fields[1] in properties:
            limits = [int(n, 16) for n in fields[0].split('..')]
            properties[fields[1]].append((limits[0], limits[-1]))
    text = '// Generated by tools/generate_unicode_lowercase.py. Unicode 16.0.0; see Shared/licenses/Unicode-3.0.txt.\npackage org.localverify.record\ninternal object UnicodeCaseData {\n'
    encoded = ';'.join(f'{k:x}='+','.join(f'{v:x}' for v in values) for k,values in mapping.items())
    text += '    const val mappings = '+json.dumps(encoded)+'\n'
    for name, ranges in properties.items():
        encoded = ';'.join(f'{a:x},{b:x}' for a,b in sorted(ranges))
        text += '    const val '+name+' = '+json.dumps(encoded)+'\n'
    text += '}\n'
    rows = [dict(id=f'lowercase-U+{k:04X}', indicatorKind='domain-name:value', indicatorValue='a'+''.join(chr(v) for v in values)+'a.invalid', text=json.dumps({'domain':'a'+chr(k)+'a.invalid'},ensure_ascii=False,separators=(',',':')), expected=1, matchType='structured') for k,values in mapping.items()]
    return {
        ROOT/'Shared/record-engine/src/commonMain/kotlin/org/localverify/record/UnicodeCaseData.kt':text,
        ROOT/'Fixtures/record-engine-unicode-mappings.json':json.dumps(rows,ensure_ascii=False,indent=2)+'\n',
    }

if __name__ == '__main__':
    parser = argparse.ArgumentParser(); parser.add_argument('--check', action='store_true'); args = parser.parse_args()
    for path, text in generate().items():
        if args.check:
            if path.read_text() != text: raise SystemExit('Stale Unicode output: '+str(path))
        else: path.write_text(text)
    print('Unicode 16.0.0 tables and mapping fixtures verified.' if args.check else 'Unicode 16.0.0 tables and mapping fixtures generated.')
