import XCTest
@testable import TriageCore

final class AnalysisProgressTests: XCTestCase {
    func testRepresentativeLogWithBundledIndicators() throws {
        let root = URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent()
        let data = try ThreatUpdates.feeds.map { try Data(contentsOf: root.appendingPathComponent("iOS/App/ThreatData/\($0.resource).stix2")) }
        let indicators = try ThreatUpdates.combine(data, checkedAt: nil).indicators
        let text = String(repeating: "2026-09-05 19:00:00 normal process activity at benign.example\n", count: 4000)
        let start = Date()
        XCTAssertTrue(try Analyzer.scan(text, source: "representative.log", indicators: indicators).isEmpty)
        print("Representative \(text.utf8.count)-byte log: \(Date().timeIntervalSince(start)) seconds")
        XCTAssertLessThan(Date().timeIntervalSince(start), 3, "Synthetic log scan regressed to per-indicator/per-line work")
    }
    func testTokenOptimizationPreservesRegexBoundariesAndUnicode() throws {
        let indicators = [
            Indicator(id: "d", kind: "domain-name:value", value: "ask.example"),
            Indicator(id: "p", kind: "process:name", value: "badproc"),
            Indicator(id: "u", kind: "url:value", value: "https://evil.example/a?x=1"),
            Indicator(id: "f", kind: "file:path", value: "/tmp/a file"),
            Indicator(id: "unicode", kind: "file:name", value: "évil")
        ]
        let lines = ["asK.example", "aſk.example", "ASK.EXAMPLE", "not-ask.example", "ask.example.benign", "ask.example.", "(ask.example)", "badproc", "badprocess", "badproc/next", "https://evil.example/a?x=1", "https://evil.example/a?x=12", "/tmp/a file", "évil", "e\u{301}vil"]
        let found = try Analyzer.scan(lines.joined(separator: "\n"), source: "boundary.log", indicators: indicators)
        var expected = Set<String>()
        for indicator in indicators {
            let domain = indicator.kind == "domain-name:value"
            let boundary = domain ? "A-Za-z0-9_.-" : "A-Za-z0-9_./:%?=&-"
            let regex = try NSRegularExpression(pattern: "(?<![\(boundary)])\(NSRegularExpression.escapedPattern(for: indicator.value))(?![\(boundary)])", options: domain ? [.caseInsensitive] : [])
            for (index, line) in lines.enumerated() where regex.firstMatch(in: line, range: NSRange(line.startIndex..., in: line)) != nil {
                expected.insert(indicator.id + ":line \(index + 1)")
            }
        }
        XCTAssertEqual(Set(found.map { $0.rule + ":" + $0.record }), expected)
    }
    func testLargeSyntheticLogReportsProgressWithinAFile() throws {
        let root = URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent()
        let data = try ThreatUpdates.feeds.map { try Data(contentsOf: root.appendingPathComponent("iOS/App/ThreatData/\($0.resource).stix2")) }
        let indicators = try ThreatUpdates.combine(data, checkedAt: nil).indicators
        let text = String(repeating: "2026-09-05 19:00:00 normal process activity at benign.example\n", count: 250000)
        var progressCount = 0
        let start = Date()
        XCTAssertTrue(try Analyzer.scan(text, source: "large-synthetic.log", indicators: indicators, progress: { _ in progressCount += 1 }).isEmpty)
        XCTAssertGreaterThan(progressCount, 100)
        print("Large synthetic \(text.utf8.count)-byte log: \(Date().timeIntervalSince(start)) seconds")
        XCTAssertLessThan(Date().timeIntervalSince(start), 15)
    }
    func testCancellationDuringTextIndexing() async {
        let task = Task {
            try Analyzer.scan(String(repeating: "benign.example\n", count: 100000), source: "cancel.log", indicators: IndicatorSet.demo.indicators, progress: { _ in
                withUnsafeCurrentTask { $0?.cancel() }
            })
        }
        do { _ = try await task.value; XCTFail("Cancelled scan must not succeed") }
        catch { XCTAssertTrue(error is CancellationError) }
    }
    func testSkippedArchivePayloadStillReportsReadProgress() throws {
        let folder = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        try FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: folder) }
        // Entirely generated bytes, never copied device evidence.
        try Data(repeating: 0, count: 2_000_000).write(to: folder.appendingPathComponent("unsupported.bin"))
        let archive = folder.appendingPathComponent("synthetic.tar.gz")
        let tar = Process(); tar.executableURL = URL(fileURLWithPath: "/usr/bin/tar")
        tar.arguments = ["-czf", archive.path, "-C", folder.path, "unsupported.bin"]
        try tar.run(); tar.waitUntilExit(); XCTAssertEqual(tar.terminationStatus, 0)
        var readings: [Int64] = []; var skipped = 0
        try Archive.walk(archive, progress: { bytes, _ in readings.append(bytes) }) { path, data, reason in
            XCTAssertNil(data); XCTAssertNotNil(reason)
            if path == "unsupported.bin" { skipped += 1 }
        }
        XCTAssertEqual(skipped, 1)
        XCTAssertGreaterThan(readings.count, 20)
        XCTAssertEqual(readings, readings.sorted())
        XCTAssertGreaterThanOrEqual(readings.last ?? 0, 2_000_000)
        var events: [String] = []
        let report = try Analyzer.analyze(archive: archive, indicators: .demo, previous: Report(caseID: "synthetic", indicators: .demo), progress: { events.append($0) }) { _ in }
        XCTAssertTrue(events.contains { $0.contains("Verifying original") })
        XCTAssertTrue(events.contains { $0.contains("Reading archive") })
        XCTAssertEqual(report.status, "Analysis incomplete")
    }
}
